# Generated by Django 5.0.1 on 2024-02-29 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_formsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.type')),
            ],
        ),
        migrations.CreateModel(
            name='clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.type')),
            ],
        ),
        migrations.CreateModel(
            name='electronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.type')),
            ],
        ),
        migrations.CreateModel(
            name='toys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('price', models.FloatField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.category')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.type')),
            ],
        ),
    ]
