# Generated by Django 5.0.1 on 2024-02-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_accessories_clothes_electronics_toys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothes',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clothes',
            name='type',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='category',
        ),
        migrations.RemoveField(
            model_name='electronics',
            name='type',
        ),
        migrations.RemoveField(
            model_name='toys',
            name='category',
        ),
        migrations.RemoveField(
            model_name='toys',
            name='type',
        ),
        migrations.DeleteModel(
            name='accessories',
        ),
        migrations.DeleteModel(
            name='clothes',
        ),
        migrations.DeleteModel(
            name='electronics',
        ),
        migrations.DeleteModel(
            name='toys',
        ),
    ]
